services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin@123456
      - MYSQL_ROOT_HOST=0.0.0.0
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - default
#  backend-service:
#    container_name: backend-service
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - default
#  web:
#    image: "e-ecommerce:0.0.1"
#    ports:
#      - "8080:8080"
#    container_name: e-ecommerce
#    env_file:
#      - ./.env.example


networks:
  default:
    name: backend-service

volumes:
  mysql_data: